version: "3.3"

services:
  api-php:
    build: ./api-php/
    volumes:
      - ./api-php/src:/var/www/html
    ports:
      - 8000:8080
    networks:
      - backend
  api-node:
    build: ./api-node/
    volumes:
      - ./api-node/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8001
    networks:
      - backend
  api-python:
    build: ./api-python/
    volumes:
      - ./api-python/app:/app
    ports:
      - 8002:8002
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=8002
    networks:
      - backend
  proxy:
    image: nginx:alpine
    depends_on:
      - api-node
      - api-php
      - api-python
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
  # postgres:
  # nextjs:
networks:
  backend:
    driver: "bridge"
